export const MOCK_DB = {
  doctors: [
    {
      id: "d1",
      userId: "u1",
      firstName: "Adaeze",
      lastName: "Okonkwo",
      specialization: "Cardiology",
      licenseNumber: "DOC-001",
      yearsOfExperience: 10,
      hospitalAffiliation: "Lagos Island General Hospital",
      consultationFee: 25000,
      phoneNumber: "+2348011111111",
      isVerified: true,
      isActive: true,
      createdAt: "2025-01-10",
    },
    {
      id: "d2",
      userId: "u2",
      firstName: "Emeka",
      lastName: "Nwosu",
      specialization: "General Practice",
      licenseNumber: "DOC-002",
      yearsOfExperience: 6,
      hospitalAffiliation: "LUTH",
      consultationFee: 15000,
      phoneNumber: "+2348022222222",
      isVerified: true,
      isActive: true,
      createdAt: "2025-02-01",
    },
    {
      id: "d3",
      userId: "u3",
      firstName: "Chinwe",
      lastName: "Eze",
      specialization: "Pediatrics",
      licenseNumber: "DOC-003",
      yearsOfExperience: 8,
      hospitalAffiliation: "National Hospital Abuja",
      consultationFee: 20000,
      phoneNumber: "+2348033333333",
      isVerified: false,
      isActive: true,
      createdAt: "2025-02-15",
    },
  ],
  drugs: [
    {
      id: "dr1",
      pharmacyId: "ph1",
      medicineName: "Amlodipine",
      dosage: "5mg",
      manufacturer: "Pfizer",
      quantity: 200,
      price: 1500,
      expiryDate: "2026-12-01",
      requiresPrescription: true,
    },
    {
      id: "dr2",
      pharmacyId: "ph1",
      medicineName: "Lisinopril",
      dosage: "10mg",
      manufacturer: "Merck",
      quantity: 150,
      price: 2000,
      expiryDate: "2026-10-15",
      requiresPrescription: true,
    },
    {
      id: "dr3",
      pharmacyId: "ph2",
      medicineName: "Paracetamol",
      dosage: "500mg",
      manufacturer: "GSK",
      quantity: 500,
      price: 300,
      expiryDate: "2027-06-01",
      requiresPrescription: false,
    },
    {
      id: "dr4",
      pharmacyId: "ph1",
      medicineName: "Metformin",
      dosage: "500mg",
      manufacturer: "Teva",
      quantity: 300,
      price: 800,
      expiryDate: "2026-08-20",
      requiresPrescription: true,
    },
  ],
  prescriptions: [
    {
      id: "rx1",
      doctorId: "d1",
      patientId: "p1",
      appointmentId: "apt1",
      diagnosis: "Hypertension",
      instructions: "Take with food",
      notes: "Monitor BP weekly",
      status: "active",
      createdAt: "2025-02-10",
      items: [
        {
          id: "i1",
          drugId: "dr1",
          dosage: "5mg",
          duration: "30 days",
          quantityPrescribed: 30,
        },
      ],
    },
    {
      id: "rx2",
      doctorId: "d2",
      patientId: "p1",
      appointmentId: "apt2",
      diagnosis: "Diabetes Type 2",
      instructions: "Before meals",
      notes: "",
      status: "active",
      createdAt: "2025-02-18",
      items: [
        {
          id: "i2",
          drugId: "dr4",
          dosage: "500mg",
          duration: "90 days",
          quantityPrescribed: 90,
        },
      ],
    },
  ],
  appointments: [
    {
      id: "apt1",
      patientId: "p1",
      doctorId: "d1",
      date: "2026-02-28",
      time: "10:00 AM",
      reason: "Chest pain follow-up",
      status: "confirmed",
      type: "in-person",
    },
    {
      id: "apt2",
      patientId: "p1",
      doctorId: "d2",
      date: "2026-03-05",
      time: "02:00 PM",
      reason: "Routine checkup",
      status: "pending",
      type: "in-person",
    },
  ],
  payments: [
    {
      id: "pay1",
      patientId: "p1",
      doctorId: "d1",
      amount: 25000,
      status: "paid",
      method: "card",
      createdAt: "2025-02-10",
    },
    {
      id: "pay2",
      patientId: "p1",
      doctorId: "d2",
      amount: 15000,
      status: "pending",
      method: "transfer",
      createdAt: "2025-02-18",
    },
  ],
  notifications: [
    {
      id: "n1",
      userId: "u4",
      type: "appointment_reminder",
      message: "Reminder: Appointment with Dr. Okonkwo tomorrow at 10:00 AM",
      read: false,
      createdAt: "2025-02-27",
    },
    {
      id: "n2",
      userId: "u4",
      type: "prescription_ready",
      message: "Prescription issued by Dr. Nwosu",
      read: true,
      createdAt: "2025-02-18",
    },
  ],
  pharmacies: [
    {
      id: "ph1",
      pharmacyName: "HealthBridge Pharmacy Lekki",
      address: "14 Admiralty Way, Lekki Phase 1, Lagos",
      phoneNumber: "+2348011112222",
      operatingHours: "8AM – 10PM",
      isVerified: true,
      lat: 6.4478,
      lng: 3.4723,
      drugs: ["Amlodipine", "Paracetamol", "Metformin"],
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: "ph2",
      pharmacyName: "CarePoint Pharmacy VI",
      address: "3 Ozumba Mbadiwe Ave, Victoria Island, Lagos",
      phoneNumber: "+2348022223333",
      operatingHours: "7AM – 9PM",
      isVerified: true,
      lat: 6.4295,
      lng: 3.4108,
      drugs: ["Lisinopril", "Paracetamol", "Amoxicillin"],
      deliveryAvailable: false,
      rating: 4.5,
    },
    {
      id: "ph3",
      pharmacyName: "MedPlus Pharmacy Ikeja",
      address: "45 Allen Avenue, Ikeja, Lagos",
      phoneNumber: "+2348033334444",
      operatingHours: "8AM – 8PM",
      isVerified: true,
      lat: 6.6015,
      lng: 3.3512,
      drugs: ["Metformin", "Amlodipine", "Ibuprofen"],
      deliveryAvailable: true,
      rating: 4.6,
    },
    {
      id: "ph4",
      pharmacyName: "Alpha Pharmacy Surulere",
      address: "20 Bode Thomas St, Surulere, Lagos",
      phoneNumber: "+2348044445555",
      operatingHours: "8AM – 9PM",
      isVerified: false,
      lat: 6.5022,
      lng: 3.3611,
      drugs: ["Paracetamol", "Amoxicillin", "Ciprofloxacin"],
      deliveryAvailable: true,
      rating: 4.2,
    },
    {
      id: "ph5",
      pharmacyName: "Wellspring Pharmacy Abuja",
      address: "Plot 1234 Wuse Zone 3, Abuja",
      phoneNumber: "+2348055556666",
      operatingHours: "9AM – 8PM",
      isVerified: true,
      lat: 9.0765,
      lng: 7.3986,
      drugs: ["Amlodipine", "Lisinopril", "Metformin"],
      deliveryAvailable: false,
      rating: 4.7,
    },
  ],
};
