version: "3.8"

services:
  user-profile-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: userprofile-service
    ports:
      - "${PORT:-3001}:3001"
    env_file:
     - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - authservice-network

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: healthbridge-profiles-db
    environment:
      POSTGRES_DB: healthbridge_profiles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
