services:
  user-profile-service:
    build:
      context: .
      target: development  # swap to 'production' for prod
      dockerfile: dockerfile
    container_name: userprofile-service
    ports:
      - "${PORT:-3007}:3007"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - profile-network

  postgres:
    image: postgres:15-alpine
    container_name: healthbridge-profiles-db
    environment:
      POSTGRES_DB: healthbridge_profiles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profile-network

networks:
  profile-network:
    driver: bridge

volumes:
  postgres_data:
    name: healthbridge-profiles-db-data
    driver: local
  redis_data:
    name: healthbridge-redis-data
    driver: local
  rabbitmq_data:
    name: healthbridge-rabbitmq-data
    driver: local

networks:
  microservice-network:
    name: microservice-network
    external: true
    driver: bridge

